version: '3.8'

services:
  rekor:
    container_name: sigstore-rekor
    build:
      context: ./rekor
      dockerfile: Dockerfile-rekor
    ports:
    - "3000:3000" 
    networks:
      - sigstore-network
    restart: unless-stopped
  
  dex:
    container_name: sigstore-dex
    build:
      context: ./dex
      dockerfile: Dockerfile
    env_file:
      - ./dex/.env
    ports:
    - "5556:5556" 
    networks:
      - sigstore-network
    restart: unless-stopped

  fulcio:
    container_name: sigstore-fulcio
    build:
      context: ./fulcio
      dockerfile: Dockerfile
    volumes:
      - fulcio-data:/shared
    ports:
    - "5000:5000" 
    networks:
      - sigstore-network
    restart: unless-stopped

  ctlog:
    container_name: sigstore-ctlog
    build:
      context: ./ctlog
      dockerfile: Dockerfile
    volumes:
      - fulcio-data:/shared
    networks:
      - sigstore-network
    restart: unless-stopped

  cosign:
    container_name: sigstore-cosign
    build:
      context: ./cosign
      dockerfile: Dockerfile
    volumes:
      - ctlog-data:/shared/ctlog-config
    networks:
      - sigstore-network
    restart: unless-stopped

volumes:
  fulcio-data:
  ctlog-data:

networks:
  sigstore-network:
    driver: bridge